language: python

python:
    - 2.7

before_script:
  - curl http://www.dlvsystem.com/files/dlv.i386-linux-elf-static.bin
  - mv dlv.i386-linux-elf-static.bin /usr/local/bin/dlv

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

branches:
    only:
        - master

notifications:
    email:
        - mkelly.deft@gmail.com
